import { FoodItem, Order, TimeSlot, AnalyticsData } from './types';

export const menuItems: FoodItem[] = [
  // Breakfast
  {
    id: '1',
    name: 'Masala Dosa',
    description: 'Crispy rice crepe with spiced potato filling, served with sambar and chutney',
    price: 45,
    category: 'breakfast',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=400&h=300&fit=crop',
    available: true,
    preparationTime: 10,
  },
  {
    id: '2',
    name: 'Poha',
    description: 'Flattened rice with peanuts, curry leaves, and spices',
    price: 30,
    category: 'breakfast',
    image: 'https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?w=400&h=300&fit=crop',
    available: true,
    preparationTime: 8,
  },
  {
    id: '3',
    name: 'Idli Sambar',
    description: 'Steamed rice cakes served with sambar and coconut chutney',
    price: 35,
    category: 'breakfast',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400&h=300&fit=crop',
    available: true,
    preparationTime: 5,
  },
  // Main Course
  {
    id: '4',
    name: 'Veg Biryani',
    description: 'Fragrant basmati rice with mixed vegetables and aromatic spices',
    price: 80,
    category: 'main-course',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&h=300&fit=crop',
    available: true,
    preparationTime: 15,
  },
  {
    id: '5',
    name: 'Chicken Curry Rice',
    description: 'Tender chicken in rich gravy served with steamed rice',
    price: 100,
    category: 'main-course',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400&h=300&fit=crop',
    available: true,
    preparationTime: 15,
  },
  {
    id: '6',
    name: 'Paneer Butter Masala',
    description: 'Cottage cheese in creamy tomato gravy with naan',
    price: 90,
    category: 'main-course',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&h=300&fit=crop',
    available: false,
    preparationTime: 12,
  },
  {
    id: '7',
    name: 'Chole Bhature',
    description: 'Spiced chickpea curry with fried bread',
    price: 70,
    category: 'main-course',
    image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=400&h=300&fit=crop',
    available: true,
    preparationTime: 10,
  },
  // Snacks
  {
    id: '8',
    name: 'Samosa',
    description: 'Crispy pastry filled with spiced potatoes and peas',
    price: 15,
    category: 'snacks',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=300&fit=crop',
    available: true,
    preparationTime: 5,
  },
  {
    id: '9',
    name: 'Pav Bhaji',
    description: 'Spiced vegetable mash served with buttered bread rolls',
    price: 50,
    category: 'snacks',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400&h=300&fit=crop',
    available: true,
    preparationTime: 8,
  },
  {
    id: '10',
    name: 'Vada Pav',
    description: 'Mumbai-style spiced potato fritter in a bun',
    price: 25,
    category: 'snacks',
    image: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=400&h=300&fit=crop',
    available: true,
    preparationTime: 5,
  },
  // Beverages
  {
    id: '11',
    name: 'Masala Chai',
    description: 'Traditional Indian spiced tea',
    price: 15,
    category: 'beverages',
    image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&h=300&fit=crop',
    available: true,
    preparationTime: 3,
  },
  {
    id: '12',
    name: 'Cold Coffee',
    description: 'Chilled coffee blended with milk and ice cream',
    price: 40,
    category: 'beverages',
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=300&fit=crop',
    available: true,
    preparationTime: 5,
  },
  {
    id: '13',
    name: 'Fresh Lime Soda',
    description: 'Refreshing lime juice with soda water',
    price: 25,
    category: 'beverages',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=400&h=300&fit=crop',
    available: true,
    preparationTime: 2,
  },
  {
    id: '14',
    name: 'Mango Lassi',
    description: 'Creamy yogurt smoothie with fresh mango',
    price: 45,
    category: 'beverages',
    image: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=400&h=300&fit=crop',
    available: false,
    preparationTime: 4,
  },
  // Desserts
  {
    id: '15',
    name: 'Gulab Jamun',
    description: 'Soft milk dumplings soaked in rose-flavored syrup',
    price: 30,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1666190094712-385d4d0b15e0?w=400&h=300&fit=crop',
    available: true,
    preparationTime: 2,
  },
  {
    id: '16',
    name: 'Ice Cream Sundae',
    description: 'Vanilla ice cream with chocolate sauce and nuts',
    price: 50,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&h=300&fit=crop',
    available: true,
    preparationTime: 3,
  },
  // Today's Special
  {
    id: '17',
    name: 'Thali Combo',
    description: 'Complete meal with dal, sabzi, rice, roti, and dessert',
    price: 120,
    category: 'todays-special',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop',
    available: true,
    preparationTime: 15,
  },
  {
    id: '18',
    name: 'Chef Special Pasta',
    description: 'Creamy pasta with vegetables in white sauce',
    price: 85,
    category: 'todays-special',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=300&fit=crop',
    available: true,
    preparationTime: 12,
  },
];

export const timeSlots: TimeSlot[] = [
  { id: '1', time: '11:00 - 11:15', available: true },
  { id: '2', time: '11:15 - 11:30', available: true },
  { id: '3', time: '11:30 - 11:45', available: true },
  { id: '4', time: '11:45 - 12:00', available: false },
  { id: '5', time: '12:00 - 12:15', available: true },
  { id: '6', time: '12:15 - 12:30', available: true },
  { id: '7', time: '12:30 - 12:45', available: true },
  { id: '8', time: '12:45 - 13:00', available: true },
  { id: '9', time: '13:00 - 13:15', available: true },
  { id: '10', time: '13:15 - 13:30', available: true },
  { id: '11', time: '13:30 - 13:45', available: false },
  { id: '12', time: '13:45 - 14:00', available: true },
];

export const mockOrders: Order[] = [
  {
    id: 'ORD-001',
    studentId: 'STU-001',
    studentName: 'Rahul Sharma',
    items: [
      { foodItem: menuItems[0], quantity: 1 },
      { foodItem: menuItems[10], quantity: 2 },
    ],
    totalAmount: 75,
    pickupTime: '12:00 - 12:15',
    status: 'preparing',
    createdAt: new Date(Date.now() - 1000 * 60 * 15),
  },
  {
    id: 'ORD-002',
    studentId: 'STU-002',
    studentName: 'Priya Patel',
    items: [
      { foodItem: menuItems[3], quantity: 1 },
      { foodItem: menuItems[11], quantity: 1 },
    ],
    totalAmount: 120,
    pickupTime: '12:15 - 12:30',
    status: 'pending',
    createdAt: new Date(Date.now() - 1000 * 60 * 5),
  },
  {
    id: 'ORD-003',
    studentId: 'STU-003',
    studentName: 'Amit Kumar',
    items: [
      { foodItem: menuItems[7], quantity: 2 },
      { foodItem: menuItems[12], quantity: 1 },
    ],
    totalAmount: 55,
    pickupTime: '12:00 - 12:15',
    status: 'ready',
    createdAt: new Date(Date.now() - 1000 * 60 * 25),
  },
  {
    id: 'ORD-004',
    studentId: 'STU-001',
    studentName: 'Rahul Sharma',
    items: [
      { foodItem: menuItems[16], quantity: 1 },
    ],
    totalAmount: 120,
    pickupTime: '13:00 - 13:15',
    status: 'completed',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
];

export const analyticsData: AnalyticsData = {
  totalOrdersToday: 156,
  revenueToday: 12450,
  averageOrderValue: 80,
  peakTimeSlot: '12:00 - 12:30',
  popularItems: [
    { name: 'Masala Dosa', count: 45 },
    { name: 'Veg Biryani', count: 38 },
    { name: 'Samosa', count: 32 },
    { name: 'Masala Chai', count: 28 },
    { name: 'Thali Combo', count: 24 },
  ],
  ordersByTimeSlot: [
    { slot: '11:00', orders: 12 },
    { slot: '11:30', orders: 18 },
    { slot: '12:00', orders: 42 },
    { slot: '12:30', orders: 38 },
    { slot: '13:00', orders: 28 },
    { slot: '13:30', orders: 18 },
  ],
  wastageReduction: 35,
};

export const categoryLabels: Record<string, string> = {
  'breakfast': 'Breakfast',
  'main-course': 'Main Course',
  'snacks': 'Snacks',
  'beverages': 'Beverages',
  'desserts': 'Desserts',
  'todays-special': "Today's Special",
};
